binary_data_dir: data/binary/df2k4x
patch_size: 16                      # 160
crop_size: 32                       # 320
thresh_size: 16                     # 160
test_crop_size: [ 5000, 5000 ]
test_thresh_size: 0
valid_steps: 4
num_sanity_val_steps: 4
eval_batch_size: 1
test_batch_size: 1
sr_scale: 4